import { v4 as uuid } from "uuid";
export const shows = [
  {
    id: uuid(),
    date: "13/07/24",
    year: "2024",
    time: "",
    location: "Paris, France",
    venue: "Le Truskel",
    infoLink: "",
    isInfo: false,
  },
  {
    id: uuid(),
    date: "22/06/24",
    year: "2024",
    time: "",
    location: "Villemoisson sur Orge, France",
    venue: "Fet'estival",
    infoLink: "google.com",
    isInfo: true,
  },
  {
    id: uuid(),
    date: "26/03/24",
    year: "2024",
    time: "",
    location: "Paris, France",
    venue: "Les disquaires",
    infoLink: "",
    isInfo: false,
  },
  {
    id: uuid(),
    date: "17/12/22",
    year: "2022",
    time: "",
    location: "Voisin le Bretonneux, France",
    venue: "Met' Assos",
    infoLink: "",
    isInfo: false,
  },
  {
    id: uuid(),
    date: "16/12/22",
    year: "2022",
    time: "",
    location: "Paris, France",
    venue: "Le Truskel",
    infoLink: "",
    isInfo: false,
  },
  {
    id: uuid(),
    date: "20/02/20",
    year: "2020",
    time: "",
    location: "Paris, France",
    venue: "Le Truskel",
    infoLink: "",
    isInfo: false,
  },
  {
    id: uuid(),
    date: '19/01/19',
    year: '2019',
    time: '',
    location: 'Villeneuve la Garennes, France',
    venue: 'Virtuoz Club',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '06/04/18',
    year: '2018',
    time: '',
    location: 'Villeneuve la Garennes, France',
    venue: 'Virtuoz Club',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '13/01/18',
    year: '2018',
    time: '',
    location: 'Meaux, France',
    venue: 'Espace Caravelle',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '05/08/17',
    year: '2017',
    time: '',
    location: 'Ascot, UK',
    venue: 'Silwood Park',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '21/06/17',
    year: '2017',
    time: '',
    location: 'Meaux, France',
    venue: 'Place Darnetal',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '11/07/14',
    year: '2014',
    time: '',
    location: 'Jussieu, France',
    venue: 'Bar',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '21/06/14',
    year: '2014',
    time: '',
    location: 'Meaux, France',
    venue: 'Place Darnetal',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '21/06/14',
    year: '2014',
    time: '',
    location: 'Meaux, France',
    venue: 'Place Saint Etienne',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '09/06/14',
    year: '2014',
    time: '',
    location: 'Cergy, France',
    venue: 'Maison des étudiants',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '04/06/14',
    year: '2014',
    time: '',
    location: 'Paris, France',
    venue: 'UPMC',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '02/04/14',
    year: '2014',
    time: '',
    location: 'Paris, France',
    venue: 'Le Buzz',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '02/04/14',
    year: '2014',
    time: '',
    location: 'Paris, France',
    venue: 'Le Buzz',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '22/06/13',
    year: '2013',
    time: '',
    location: 'Ouarville, France',
    venue: 'Fête de la musique',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '29/06/12',
    year: '2012',
    time: '',
    location: 'Magny-le-Hongre, France',
    venue: 'File 7',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '13/04/12',
    year: '2012',
    time: '',
    location: 'Magny-le-Hongre, France',
    venue: 'File 7',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '19/11/11',
    year: '2011',
    time: '',
    location: 'Paris, France',
    venue: 'Scène Bastille (Virtuose Radio)',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '25/06/11',
    year: '2011',
    time: '',
    location: 'Ouarville, France',
    venue: 'Salle des 4 vents',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '21/06/11',
    year: '2011',
    time: '',
    location: 'Meaux, France',
    venue: 'L\'Arum',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '17/06/11',
    year: '2011',
    time: '',
    location: 'Paris, France',
    venue: 'Le Bricabrac',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '09/03/11',
    year: '2011',
    time: '',
    location: 'Paris, France',
    venue: 'Gibus (Festival Emergenza)',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '16/12/10',
    year: '2010',
    time: '',
    location: 'Meaux, France',
    venue: 'Frot',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '27/11/2010',
    year: '2010',
    time: '',
    location: 'Meaux, France',
    venue: 'Espace Caravelle',
    infoLink: '',
    isInfo: false,
  },
];

export const years = [...new Set(shows.map(show => show.year))];
export const yearsInt = years.map(Number)
// for (let show of shows) {
//   if (!years.includes(show.year)) {
//     years.push(show.year);
//   }
// }

export const musics = [
  {
    id: uuid(),
    title: "Wrong",
    artist: "Spade Diamonds",
    src: "/begining.wav",
    thumbnail: "/sd7.jpeg",
  },
  {
    id: uuid(),
    title: "Tomorrow Will Be The Same",
    artist: "Spade Diamonds",
    src: "/atonement.mp3",
    thumbnail: "/promo.jpeg",
  },
  {
    id: uuid(),
    title: "Modest Moment",
    artist: "Spade Diamonds",
    src: "/begining.wav",
    thumbnail: "/sd5.jpeg",
  },
  {
    id: uuid(),
    title: "Despite",
    artist: "Spade Diamonds",
    src: "/atonement.mp3",
    thumbnail: "/sd6.jpeg",
  },
];

export const videos = [
  {
    id: uuid(),
    youtubeId: "3XTls-Wl4YM",
  },
  {
    id: uuid(),
    youtubeId: "wfbKvRoIeZg",
  },
  // {
  //   id: uuid(),
  //   youtubeId: 'lEmsZZuWJPg',
  // },
  // {
  //   id: uuid(),
  //   youtubeId: 'd2A6kOnFSxs',
  // },
  // {
  //   id: uuid(),
  //   youtubeId: 'ypFYE2ZZJHg',
  // },
  // {
  //   id: uuid(),
  //   youtubeId: 'pyv_s5rPY_8',
  // },
];
