import { v4 as uuid } from "uuid";
export const shows = [
  {
    id: uuid(),
    date: "2025-10-13",
    year: "2025",
    time: "08:30 PM",
    location: "Paris, France",
    venue: "Stade de France",
    infoLink: "https://www.stadefrance.com/fr",
    isInfo: true,
  },
  {
    id: uuid(),
    date: "2025-09-02",
    year: "2025",
    time: "09:00 PM",
    location: "London, UK",
    venue: "Royal Albert Hall",
    infoLink: "https://www.royalalberthall.com/tickets",
    isInfo: true,
  },
  {
    id: uuid(),
    date: "2024-07-13",
    year: "2024",
    time: "",
    location: "Paris, France",
    venue: "Le Truskel",
    infoLink: "",
    isInfo: false,
  },
  {
    id: uuid(),
    date: "2024-06-22",
    year: "2024",
    time: "",
    location: "Villemoisson sur Orge, France",
    venue: "Fet'estival",
    infoLink: "google.com",
    isInfo: true,
  },
  {
    id: uuid(),
    date: "2024-03-26",
    year: "2024",
    time: "",
    location: "Paris, France",
    venue: "Les disquaires",
    infoLink: "",
    isInfo: false,
  },
  {
    id: uuid(),
    date: "2022-12-17",
    year: "2022",
    time: "",
    location: "Voisin le Bretonneux, France",
    venue: "Met' Assos",
    infoLink: "",
    isInfo: false,
  },
  {
    id: uuid(),
    date: "2022-12-16",
    year: "2022",
    time: "",
    location: "Paris, France",
    venue: "Le Truskel",
    infoLink: "",
    isInfo: false,
  },
  {
    id: uuid(),
    date: "2020-02-20",
    year: "2020",
    time: "",
    location: "Paris, France",
    venue: "Le Truskel",
    infoLink: "",
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2019-01-19',
    year: '2019',
    time: '',
    location: 'Villeneuve la Garennes, France',
    venue: 'Virtuoz Club',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2018-04-06',
    year: '2018',
    time: '',
    location: 'Villeneuve la Garennes, France',
    venue: 'Virtuoz Club',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2018-01-13',
    year: '2018',
    time: '',
    location: 'Meaux, France',
    venue: 'Espace Caravelle',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2017-08-05',
    year: '2017',
    time: '',
    location: 'Ascot, UK',
    venue: 'Silwood Park',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2017-06-21',
    year: '2017',
    time: '',
    location: 'Meaux, France',
    venue: 'Place Darnetal',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2014-07-11',
    year: '2014',
    time: '',
    location: 'Jussieu, France',
    venue: 'Bar',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2014-06-21',
    year: '2014',
    time: '',
    location: 'Meaux, France',
    venue: 'Place Darnetal',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2014-06-21',
    year: '2014',
    time: '',
    location: 'Meaux, France',
    venue: 'Place Saint Etienne',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2014-06-09',
    year: '2014',
    time: '',
    location: 'Cergy, France',
    venue: 'Maison des étudiants',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2014-06-04',
    year: '2014',
    time: '',
    location: 'Paris, France',
    venue: 'UPMC',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2024-04-02',
    year: '2014',
    time: '',
    location: 'Paris, France',
    venue: 'Le Buzz',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2013-06-22',
    year: '2013',
    time: '',
    location: 'Ouarville, France',
    venue: 'Fête de la musique',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2012-06-29',
    year: '2012',
    time: '',
    location: 'Magny-le-Hongre, France',
    venue: 'File 7',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2012-04-13',
    year: '2012',
    time: '',
    location: 'Magny-le-Hongre, France',
    venue: 'File 7',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2011-11-19',
    year: '2011',
    time: '',
    location: 'Paris, France',
    venue: 'Scène Bastille (Virtuose Radio)',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2011-06-25',
    year: '2011',
    time: '',
    location: 'Ouarville, France',
    venue: 'Salle des 4 vents',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2011-06-21',
    year: '2011',
    time: '',
    location: 'Meaux, France',
    venue: 'L\'Arum',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2011-06-17',
    year: '2011',
    time: '',
    location: 'Paris, France',
    venue: 'Le Bricabrac',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2011-03-09',
    year: '2011',
    time: '',
    location: 'Paris, France',
    venue: 'Gibus (Festival Emergenza)',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2010-12-16',
    year: '2010',
    time: '',
    location: 'Meaux, France',
    venue: 'Frot',
    infoLink: '',
    isInfo: false,
  },
  {
    id: uuid(),
    date: '2010-11-27',
    year: '2010',
    time: '',
    location: 'Meaux, France',
    venue: 'Espace Caravelle',
    infoLink: '',
    isInfo: false,
  },
];

export const years = [...new Set(shows.map(show => show.year))];



export const musics = [
  {
    id: uuid(),
    title: "Wrong",
    artist: "Spade Diamonds",
    src: "/begining.wav",
    thumbnail: "/sd7.jpeg",
  },
  {
    id: uuid(),
    title: "Tomorrow Will Be The Same",
    artist: "Spade Diamonds",
    src: "/atonement.mp3",
    thumbnail: "/promo.jpeg",
  },
  {
    id: uuid(),
    title: "Modest Moment",
    artist: "Spade Diamonds",
    src: "/begining.wav",
    thumbnail: "/sd5.jpeg",
  },
  {
    id: uuid(),
    title: "Despite",
    artist: "Spade Diamonds",
    src: "/atonement.mp3",
    thumbnail: "/sd6.jpeg",
  },
];

export const videos = [
  {
    id: uuid(),
    youtubeId: "3XTls-Wl4YM",
  },
  {
    id: uuid(),
    youtubeId: "wfbKvRoIeZg",
  },
  // {
  //   id: uuid(),
  //   youtubeId: 'lEmsZZuWJPg',
  // },
  // {
  //   id: uuid(),
  //   youtubeId: 'd2A6kOnFSxs',
  // },
  // {
  //   id: uuid(),
  //   youtubeId: 'ypFYE2ZZJHg',
  // },
  // {
  //   id: uuid(),
  //   youtubeId: 'pyv_s5rPY_8',
  // },
];
